name: Android CI

on:
  push:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: "Install .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: "Install Android Workload"
        run: |
          sudo dotnet workload restore BnbnavNetClient.Android/BnbnavNetClient.Android.csproj
      - name: "Build Project"
        run: dotnet build BnbnavNetClient.Android/BnbnavNetClient.Android.csproj -c Release
      - name: "Publish Project"
        run: dotnet publish BnbnavNetClient.Android/BnbnavNetClient.Android.csproj -c Release
      - uses: actions/upload-artifact@v3
        name: "Upload Artifact"
        with:
          name: "bnbnav-android"
          path: "./BnbnavNetClient/bin/Release/net7.0/"